spring.application.name=spring-gift
jwt.secret=my-jwt-secret-key-12345678901234567890
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.kakao.client-id=fe8a8b279b426bf009094e391f6a0270
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8080/oauth/kakao
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize

