spring.application.name=spring-gift
jwt.secret=${JWT_SECRET}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.config.import=optional:application-secret.properties
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.redirect-uri=${KAKAO_REDIRECT_URI}
spring.security.oauth2.client.provider.kakao.authorization-uri=${KAKAO_AUTH_URI}
spring.security.oauth2.client.provider.kakao.token-uri=${KAKAO_TOKEN_URI}
spring.security.oauth2.client.provider.kakao.user-info-uri=${KAKAO_USERINFO_URI}
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.initialization-mode=always
spring.jpa.defer-datasource-initialization=true

